stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw/test.csv
    - data/raw/train.csv
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data_preprocessing.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/features/build_features.py
    outs:
    - data/features/X_test.pkl
    - data/features/X_train.pkl
    - data/features/vectorizer.pkl
